name: Laravel CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install Composer Dependencies
        run: composer install --no-progress --prefer-dist

      - name: Copy Environment
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Install Node Dependencies
        run: npm install

      - name: Build Frontend Assets
        run: npm run build

      - name: Run Laravel Tests
        run: php artisan test

      - name: Build Docker Image
        run: docker build -t smartlaundry .
